# Generated by Django 5.1.4 on 2025-01-17 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Car',
        ),
    ]
